[project]
name = 'Captcha-Human-Verification-Existential-Crisis-Inducer'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.crosswalk-definition-ontological-confusion-generator]
path = 'contracts/crosswalk-definition-ontological-confusion-generator.clar'
clarity_version = 3
epoch = '3.2'

[contracts.robot-detection-irony-amplification-algorithm]
path = 'contracts/robot-detection-irony-amplification-algorithm.clar'
clarity_version = 3
epoch = 'latest'

[contracts.traffic-light-philosophical-ambiguity-maximizer]
path = 'contracts/traffic-light-philosophical-ambiguity-maximizer.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
